issue #105 fixed and add Exception Handling logic for TrinityConfig
microsoft/GraphEngine pull request #107
Opened 2017-06-23 14:19 UTC by jiabaohan

2017-06-23 14:19 UTC, yatli commented
[YataoBot] Can one of the admins verify this patch?

2017-06-23 14:20 UTC, msftclas commented
@jiabaohan,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-06-23 15:56 UTC, yatli commented
@jiabaohan good work, note that you don't have to close a PR and reopen it. After pushing your changes to your branch, it will be automatically appended to the currently active PR.

2017-06-23 15:56 UTC, yatli commented
ok to test!

2017-06-23 16:05 UTC, yatli requested changes

2017-06-23 16:05 UTC, yatli commented on src/Trinity.Core/Diagnostics/Log.cs
> +                Log.WriteLine(LogLevel.Error, "Failure to load config file, the default configuration takes effect");
please revise the log message a bit, like "falling back to default log behavior" -- this is because we are reporting from within `Log` and it would make more sense to elaborate why we are talking about `TrinityConfig` here.

2017-06-23 16:05 UTC, yatli commented on src/Trinity.Core/Network/ServerInfo.cs
> +            return new ServerInfo(hostName, port, assemblyPath, availabilityGroup, storageRoot, loggingLevel);
nice catch.

2017-06-23 16:05 UTC, yatli commented on src/Trinity.Core/Storage/LocalMemoryStorage/LocalMemoryStorage.cs
> +                Log.WriteLine(LogLevel.Error, "Failure to load config file, the default configuration takes effect");
same as above comment

2017-06-23 16:05 UTC, yatli commented on src/Trinity.Core/Storage/LocalMemoryStorage/LocalMemoryStorage.cs
> +            CSynchronizeStorageRoot();
CSynchronizeStorageRoot has return code. Please verify the sync result, and log errors if necessary.

2017-06-23 16:05 UTC, yatli commented on src/Trinity.Core/Trinity/Configuration/TrinityConfig.IO.cs
> +                SaveConfig(DefaultConfigFile);
public interface should not eat the exception. add a statement `throw;` in the catch block to re-throw it.
Also, revise the log message. Tell people why it fails.

2017-06-23 16:05 UTC, yatli commented on src/Trinity.Core/Trinity/Configuration/TrinityConfig.IO.cs
> +                Log.WriteLine(LogLevel.Error, "Failure to load config file, the default configuration takes effect");
revise log message, rethrow

2017-06-23 16:05 UTC, yatli commented on src/Trinity.Core/Trinity/Configuration/TrinityConfig.IO.cs
> +                Log.WriteLine(LogLevel.Error, "Failure to load config file, the default configuration takes effect");
same here.

2017-06-23 16:05 UTC, yatli commented on src/Trinity.Core/Trinity/Configuration/TrinityConfig.cs
> +                Log.WriteLine(LogLevel.Error, "Failure to load config file, the default configuration takes effect");
I have a concern that this message will be displayed multiple times by different classes. please verify.

2017-06-27 07:32 UTC, yatli approved these changes
Good work, thanks!

2017-06-27 07:47 UTC, jiabaohan commented on src/Trinity.Core/Trinity/Configuration/TrinityConfig.cs
> +                Log.WriteLine(LogLevel.Error, "Failure to load config file, the default configuration takes effect");
I verified that it works well.

2017-06-27 10:29 UTC, merged