Availability
microsoft/GraphEngine pull request #154
Opened 2018-01-31 20:54 UTC by thautwarm

dynamic loading completed

2018-02-01 01:56 UTC, yatli commented
reviewing

2018-02-01 02:18 UTC, yatli requested changes
good job red! let's work together to fix the rough edges. I'm adding some bits into the codegen as we discussed yesterday.

2018-02-01 02:18 UTC, yatli commented on src/Modules/DynamicLoading/DynamicLoading/Center.cs
> +            Console.WriteLine("tslsrcDir: " + tslsrcDir +
refactor with Log.WriteLine

2018-02-01 02:18 UTC, yatli commented on GraphEngine/PluginConfig.cs
> +﻿using System;
Why is this project moved?

2018-02-01 02:18 UTC, yatli commented on src/Modules/DynamicLoading/DynamicLoading/Center.cs
> +                Console.WriteLine(proc.StandardOutput.ReadToEnd());
refactor with Log.WriteLine

2018-02-01 02:18 UTC, yatli commented on src/Modules/DynamicLoading/DynamicLoading/Center.cs
> +            System.IO.Directory.GetFiles(CurrentVersion.TslSrcDir, "*.tsl").ToList().ForEach(Console.WriteLine);
same here

2018-02-01 02:18 UTC, yatli commented on src/Modules/DynamicLoading/DynamicLoading/Center.cs
> +                asm.GetTypes().ToList().ForEach(Console.WriteLine);
for point-free log.writeline, you can wrap up your own logging function within the class, like `void _log(string content) => Log.WriteLine(LogLevel.Info, $"{nameof(your_class)}: {0}", content);`

2018-02-01 02:18 UTC, yatli commented on src/Modules/DynamicLoading/DynamicLoading/Center.cs
> +                /// TODO: get cell_type count by `asm`.
use AssemblyUtility.GetAllClassInstances<IStorageSchema> to extract the schema from the generated assembly.

2018-02-01 02:18 UTC, yatli commented on src/Modules/Trinity.FFI/Trinity.FFI.Native/Trinity.FFI.SWIG.h
>  		printf("hey dtor\n");
dd

2018-02-01 02:18 UTC, yatli commented on src/Modules/Trinity.FFI/Trinity.FFI.Native/Trinity.FFI.SWIG.h
> +		g_TrinityInterfaces->cell_setid(m_cell, GetID());
SetID with no incoming cellid?

2018-02-01 02:18 UTC, yatli commented on src/Modules/Trinity.FFI/Trinity.FFI.PythonModule/collect.py
>  """
👍

2018-02-01 02:18 UTC, yatli commented on src/Modules/Trinity.FFI/Trinity.FFI.PythonModule/collect.py
> +    to_pymodule_dir(r'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\newtonsoft.json\9.0.1\lib\netstandard1.0',
if we assume 'dotnet' to be an available command, we can use it to query the location of the package cache.

2018-02-02 08:19 UTC, thautwarm commented
I thought an interface method `LoadGenericCell ` for `IGenericCellOperations` with arguments (storage, cellId, buff) is badly needed.
`Use, New, Save ` all load from storage only once, however there is not a proper method to apply the same way to `Save`.
To detail, we need
```C#
public unsafe ICell LoadGenericCell(byte[] buff, long cellId, ICell cell)
{
    switch ((CellType)type)
    {
        case CellType.xxx:
                fixed (byte* xxx_ptr = buff)
                    {
                        xxx_Accessor xxx_accessor = new xxx_Accessor(xxx_ptr);
                        xxx_accessor.CellID = cellId;
                        return (xxx)xxx_accessor;
                    }
               ...
    }
}
```

2018-02-02 08:22 UTC, thautwarm commented on src/Modules/Trinity.FFI/Trinity.FFI.Native/Trinity.FFI.SWIG.h
>  		printf("hey dtor\n");
qaq

2018-02-02 18:30 UTC, TaviTruman reviewed
Great design facet correction and overall enhancement. In general server-side services should at least be asynchronous if not multitasking.

2018-02-04 10:05 UTC, merged

2018-02-04 11:05 UTC, yatli commented
well done!